SELECT * FROM COUNTRY WHERE NAME IN ('SOUTH KOREA','JAPAN','CHINA');

SELECT* FROM COUNTRY WHERE POPULATION BETWEEN 40000000 AND 50000000;

SELECT * FROM COUNTRY WHERE CONTINENT NOT IN('NORTH AMERICA','EUROPE','ASIA') AND GNP (BETWEEN 100 AND 1000); 

